name: Webster_etal_2017_xyalign
channels:
- !!python/unicode
  'bioconda'
- !!python/unicode
  'r'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'bbmap=37.02=0'
- !!python/unicode
  'bwa=0.7.15=1'
- !!python/unicode
  'dropbox=5.2.1=py35_0'
- !!python/unicode
  'filechunkio=1.6=py35_0'
- !!python/unicode
  'ftputil=3.2=py35_0'
- !!python/unicode
  'pysftp=0.2.9=py35_0'
- !!python/unicode
  'samblaster=0.1.24=0'
- !!python/unicode
  'samtools=1.4=0'
- !!python/unicode
  'snakemake=3.11.2=py35_0'
- !!python/unicode
  'urllib3=1.12=py35_0'
- !!python/unicode
  'cffi=1.9.1=py35_0'
- !!python/unicode
  'cryptography=1.7.1=py35_0'
- !!python/unicode
  'curl=7.52.1=0'
- !!python/unicode
  'docutils=0.13.1=py35_0'
- !!python/unicode
  'idna=2.2=py35_0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'openjdk=8.17.0.3=1'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'paramiko=2.1.2=py35_0'
- !!python/unicode
  'pip=9.0.1=py35_1'
- !!python/unicode
  'pyasn1=0.2.3=py35_0'
- !!python/unicode
  'pycparser=2.17=py35_0'
- !!python/unicode
  'python=3.5.3=1'
- !!python/unicode
  'pyyaml=3.12=py35_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'requests=2.13.0=py35_0'
- !!python/unicode
  'setuptools=27.2.0=py35_0'
- !!python/unicode
  'six=1.10.0=py35_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py35_0'
- !!python/unicode
  'wrapt=1.10.8=py35_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zlib=1.2.8=3'
