name: xyalign_environment
channels:
- !!python/unicode
  'bioconda'
- !!python/unicode
  'r'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'bbmap=37.02=0'
- !!python/unicode
  'bcftools=1.3.1=1'
- !!python/unicode
  'bedtools=2.26.0=0'
- !!python/unicode
  'bwa=0.7.15=1'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'htslib=1.3.2=0'
- !!python/unicode
  'libxml2=2.9.3=0'
- !!python/unicode
  'platypus-variant=0.8.1=py27_0'
- !!python/unicode
  'pybedtools=0.7.9=py27_0'
- !!python/unicode
  'pysam=0.10.0=py27_2'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'sambamba=0.6.6=0'
- !!python/unicode
  'samtools=1.4=0'
- !!python/unicode
  'cairo=1.14.8=0'
- !!python/unicode
  'curl=7.52.1=0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'fontconfig=2.12.1=3'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'glib=2.50.2=1'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'matplotlib=2.0.0=np112py27_0'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'numpy=1.12.1=py27_0'
- !!python/unicode
  'openjdk=8.17.0.3=1'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pandas=0.19.2=np112py27_1'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pixman=0.34.0=0'
- !!python/unicode
  'pycairo=1.10.0=py27_0'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_2'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'qt=5.6.2=3'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'scipy=0.19.0=np112py27_0'
- !!python/unicode
  'seaborn=0.7.1=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'subprocess32=3.2.7=py27_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'zlib=1.2.8=3'
